### ISSUE TITLE
String to Array List conversion error

### ISSUE THREAD

**Issue by Seji64** [AdamGrossTX/FU.WhyAmIBlocked#2] opened 2020-07-27 20:40 UTC
Hi, i read in a blog about this small tool / script. Wanted to try it, but getting a small error:

![Anmerkung 2020-07-27 223741](https://user-images.githubusercontent.com/19726119/88589695-d1475080-d059-11ea-831a-01c8acf20648.png)

**Python Version:**
![Anmerkung 2020-07-27 22374_2](https://user-images.githubusercontent.com/19726119/88589875-166b8280-d05a-11ea-9064-e67ff0295dfd.png)

**Comment by MarkusKepert** [comment] 2020-07-27 20:57
Same here, Win 10 1909, geman language enabled. At my end it's another UID value: {fa1d81f1-57b7-4907-970a-a37d80d41304}

**Comment by AdamGrossTX** [comment] 2020-07-27 21:44
Thanks for reporting this. I ran into this error yesterday and thought it was resolved in the 1.0.0.2 release, but apparently not. I'll look into it.

**Comment by AdamGrossTX** [comment] 2020-07-27 22:08
@Seji64 & @MarkusNeviadomski Can you send me your Results.txt files so that I can target the correct blocks in my testing?

**Comment by Zharay** [comment] 2020-07-28 05:45
Same error but in english:
![image](https://user-images.githubusercontent.com/4379473/88623744-795d1980-d05a-11ea-8fdd-788c42945225.png)

And here is my results.txt
[Results.txt](https://github.com/AdamGrossTX/FU.WhyAmIBlocked/files/4986209/Results.txt)

In either case it looks like MS XPS/PDF is to blame? If that's true then why?

**Comment by AdamGrossTX** [comment] 2020-07-28 05:54
Actually Gears 5 is the block. 

Thanks for the file. I'll work in this tomorrow. In the meantime you can manually look up the GUID for Gears 5 in the appraiser.sdb.xml output file and it should show you the rules that are triggering the match.

**Comment by AdamGrossTX** [comment] 2020-07-28 14:33
> Same error but in english:
> ![image](https://user-images.githubusercontent.com/4379473/88623744-795d1980-d05a-11ea-8fdd-788c42945225.png)
> 
> And here is my results.txt
> [Results.txt](https://github.com/AdamGrossTX/FU.WhyAmIBlocked/files/4986209/Results.txt)
> 
> In either case it looks like MS XPS/PDF is to blame? If that's true then why?

Can you also post your HUMANREADABLE.XML files. The error is happening earlier in the process than I was expecting.

**Comment by helge000** [comment] 2020-07-28 16:23
These results look strange to me...  I have the same issue though I'm blocked by Windows Searchbox? ...
```text
Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData GatedBlock                             2      
SdbAppName       Windows Searchbox                      2      
SdbEntryGuid     {5e757e51-cc84-4a4a-ae70-d69a6a2b37f1} 2      
SdbAppGuid       {1b07f560-9ebf-461e-a71b-f3b2c7af46af} 2   
```
Anyway; here you go with my results and xml file if it is any help.

[HELGEPC.zip](https://github.com/AdamGrossTX/FU.WhyAmIBlocked/files/4989676/HELGEPC.zip)

**Comment by AdamGrossTX** [comment] 2020-07-28 18:01
Perfect. I was able to repro from this. It seems that it's just returning a single item in the blocked arraylist and converting the output to a string. I have a fix. Should be published shortly.

**Comment by AdamGrossTX** [comment] 2020-07-28 22:00
Fixed in latest build.

**Closed as completed by AdamGrossTX** 2020-07-28 22:00 UTC

**Comment by PathogenDavid** [comment] 2020-07-29 05:02
@helge000 FYI, I had that same block. For whatever reason `Get-FUBlocks` didn't generate `Match.txt` for it, but I guessed based on the name and it turned out to be caused by disabling Bing search with the `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search\BingSearchEnabled` registry value. Removing it and forcing the Appraiser task to re-run removed my compatibility hold.

Kind-of infuriating they'd place a compatibility hold on something like that, but I digress. Thanks so much for the tool, @AdamGrossTX, I never would've guessed that was my issue!

**Comment by AdamGrossTX** [comment] 2020-07-29 05:08
@PathogenDavid were you able to test again with the new release - 1.0.0.3? I was able to get that block to output to matches.txt after getting past the bug.

**Comment by PathogenDavid** [comment] 2020-07-29 05:09
Yup, this was on 1.0.0.3, I just created #6 for the issue.

**Comment by helge000** [comment] 2020-07-29 10:27
Sorry for off topic, but @PathogenDavid - Thanks! I turned it off but forgot about it. I guess it is save to assume MS removed this switch in 20H1.

**Comment by PathogenDavid** [comment] 2020-07-29 18:30
No problem! And yeah, [it was replaced with another one for whatever reason.](https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/)
